### ISSUE TITLE
.gif support

### ISSUE THREAD

**Issue by JannikZed** [ramiel/caravaggio#1]
Hi there,
We are already using your library in a production project with next.js and are really impressed! Helps us a lot!

My would love to raise the need for gif support somehow. Our designers love gifs :D would be amazing to send our externally hosted gifs also through our API pipeline to support caching and maybe resizing etc..

**Comment by ramiel** [comment]
Somehow I missed this issue. I apologize. I'm going to look at it soon

**Comment by ramiel** [comment]
So, to answer your question, gif is already supported but it depends on the environment. Caravaggio uses [`sharp`](https://sharp.pixelplumbing.com/) under the hood and gif output is supported if you have libvips compiled with support for `ImageMagick` or `GraphicsMagick`, installed in your environment (see [here](https://sharp.pixelplumbing.com/api-output#gif)). In an enviroment you have no control on, such as vercel, you must be lucky. As you can see in [this page](https://caravaggiosupport.vercel.app/api/support) I just deployed on Vercel, gif format is supported only as input, not output.

**Comment by ramiel** [comment]
Hello @JannikZed, I'm going to close this issue if there's nothing from your side. Can I ask, out of curoisity and if it's possible, where are you using Caravaggio? :slightly_smiling_face:

**Comment by JannikZed** [comment]
Hi Ramiel! Sure - sounds good. I can test it out soon! - we are using it here: https://pfefferundfrost.de

**Comment by ramiel** [comment]
Looks very nice! I also see you have a nice loading effect (https://pfefferundfrost.de/en/product/5-lebkuchen-in-bio-folie) and it's visually awesome.

I'm collecting some websites that use Caravaggio in order to put some testimonials on the documentation. If you agree I would like to put yours as well. Let me know
